#if !canImport(ObjectiveC)
import XCTest

extension ViewExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ViewExtensionsTests = [
        ("testFindViewController", testFindViewController),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ViewExtensionsTests.__allTests__ViewExtensionsTests),
    ]
}
#endif
