name: Tests

on: [push, pull_request]

jobs:

  tests:
    name: Mac
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Xcode Version
      run: xcodebuild -version
    - name: XC Pretty
      run: sudo gem install xcpretty-travis-formatter
    - name: Make Logs Directory
      run: mkdir logs
    - name: Test (macOS)
      run: xcodebuild build test -workspace . -scheme ViewExtensions | tee logs/xcodebuild-macos.log | xcpretty
    - name: Test (iOS)
      run: xcodebuild build test -workspace . -scheme ViewExtensions -destination "name=iPad Pro (11-inch)" | tee logs/xcodebuild-ios.log | xcpretty
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: logs
    - name: Slack Notification
      uses: elegantchaos/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: 'Tests (${{ matrix.config }})'
          mention_if: 'failure'
          url: ${{ secrets.SLACK_WEBHOOK }}
